### ISSUE TITLE
StackOverflowError in Dictionary.lookup

### ISSUE THREAD

**Issue by dklotz** [jprante/elasticsearch-analysis-baseform#8]
I'm using the plugin version from the elasticsearch-plugin-bundle 1.4.0.4 with ES 1.4.2 and I've configured a filter and analyzer like this:

``` json
"analysis": {
    "analyzer": {
        "german_foobar": {
            "tokenizer": "standard",
            "filter": [
                "german_foobar"
            ],
            "type": "custom"
        }
    },
    "filter": {
        "german_foobar": {
            "language": "de",
            "type": "baseform"
        }
    }
}
```

When I try to analyze the string "wurde zum tollen gemacht" with this analyzer, I get a StackOverflowError in Dictionary.lookup on the server:

```
Exception in thread "main" org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
    at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:92)
    at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:79)
    at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:61)
    at com.fileee.search.impl.DefaultSearchClient.analyze(DefaultSearchClient.java:389)
    at com.fileee.search.impl.DefaultSearchClient.main(DefaultSearchClient.java:696)
Caused by: java.util.concurrent.ExecutionException: java.lang.StackOverflowError
    at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:288)
    at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:261)
    at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:92)
    at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:72)
    ... 3 more
Caused by: java.lang.StackOverflowError
    at java.nio.charset.CharsetDecoder.replaceWith(CharsetDecoder.java:303)
    at java.nio.charset.CharsetDecoder.<init>(CharsetDecoder.java:207)
    at java.nio.charset.CharsetDecoder.<init>(CharsetDecoder.java:233)
    at sun.nio.cs.UTF_8$Decoder.<init>(UTF_8.java:84)
    at sun.nio.cs.UTF_8$Decoder.<init>(UTF_8.java:81)
    at sun.nio.cs.UTF_8.newDecoder(UTF_8.java:68)
    at java.lang.StringCoding.decode(StringCoding.java:213)
    at java.lang.String.<init>(String.java:451)
    at org.xbib.elasticsearch.index.analysis.baseform.Dictionary.lookup(Dictionary.java:58)
    at org.xbib.elasticsearch.index.analysis.baseform.Dictionary.lookup(Dictionary.java:59)
    at org.xbib.elasticsearch.index.analysis.baseform.Dictionary.lookup(Dictionary.java:59)
...
```

**Comment by jprante** [comment]
Thanks. 

In https://github.com/jprante/elasticsearch-plugin-bundle/blob/9bb59d91c82fa805eea5f0a593281f932b61ac17/src/main/resources/baseform/de-lemma-utf8.txt there are some stray tokens with circular entries which are not completely fixed yet. Such circular entries have same tokens on the first and on the second column (case insensitive). In order to fix such circular entries, the token that cause a StackOverflowError can be removed from the list where it appears in the first column. Removing a token from the first column means it is no longer used in order to compute a different base form.

I added a fix for "tollen" in https://github.com/jprante/elasticsearch-plugin-bundle/commit/9bb59d91c82fa805eea5f0a593281f932b61ac17 and pushed a new version 1.4.0.5

Please report issues to https://github.com/jprante/elasticsearch-plugin-bundle/issues if you use the bundle plugin.

**Comment by dklotz** [comment]
Thanks for quick reply and the update, unfortunately other words like "eine" or "ist" still cause this error (preventing us from using this otherwise really nice plugin in production). I opened a new issue at the bundle-project like you suggested (so you can probably close this one): https://github.com/jprante/elasticsearch-plugin-bundle/issues/1

**Comment by dklotz** [comment]
Closing old issues to clean up my open issue list. Probably fixed, feel free reopen if someone else has this problem.
